import type { FieldDef } from "../schema";

/** De velden die de editor voor deze pagina toont. */
export const VELDEN = [
  { key: "heroTitleStart", label: "Hero — titel (begin)", type: "text" },
  { key: "heroAccent", label: "Hero — accentwoord", type: "text" },
  { key: "heroLead", label: "Hero — introtekst", type: "textarea" },
  { key: "verwachtTitel", label: "Wat je kunt verwachten — titel", type: "text" },
  { key: "verwacht1Titel", label: "Stap 1 — titel", type: "text" },
  { key: "verwacht1Tekst", label: "Stap 1 — tekst", type: "textarea" },
  { key: "verwacht2Titel", label: "Stap 2 — titel", type: "text" },
  { key: "verwacht2Tekst", label: "Stap 2 — tekst", type: "textarea" },
  { key: "verwacht3Titel", label: "Stap 3 — titel", type: "text" },
  { key: "verwacht3Tekst", label: "Stap 3 — tekst", type: "textarea" },
  { key: "manierenKop", label: "Contactmanieren — verborgen kop (screenreader)", type: "text" },
  { key: "manier1Titel", label: "Bellen — titel", type: "text" },
  { key: "manier1Tekst", label: "Bellen — tekst", type: "textarea" },
  { key: "manier2Titel", label: "Mailen — titel", type: "text" },
  { key: "manier2Tekst", label: "Mailen — tekst", type: "textarea" },
  { key: "manier3Titel", label: "WhatsApp — titel", type: "text" },
  { key: "manier3Tekst", label: "WhatsApp — tekst", type: "textarea" },
  { key: "manier3Knop", label: "WhatsApp — knoptekst", type: "text" },
  { key: "manier4Titel", label: "Gesprek plannen — titel", type: "text" },
  { key: "manier4Tekst", label: "Gesprek plannen — tekst", type: "textarea" },
  { key: "manier4Knop", label: "Gesprek plannen — knoptekst", type: "text" },
  { key: "expertKop", label: "Contactpersoon — kopje boven de naam", type: "text" },
  { key: "adresTitel", label: "Bezoekadres — titel", type: "text" },
  { key: "adresRegel", label: "Bezoekadres — regel", type: "text" },
  { key: "ctaTitel", label: "Slot-CTA — titel", type: "text" },
  { key: "heroKicker", label: "Hero — kicker", type: "text" },
  { key: "linkedinLabel", label: "Sociale kaart — titel", type: "text" },
  { key: "linkedinKnop", label: "Sociale kaart — knoptekst", type: "text" },
  { key: "casesKnop", label: "Sociale kaart — link naar klantverhalen", type: "text" },
  { key: "formTitel", label: "Formulier — titel", type: "text" },
  {
    key: "formSubDienst",
    label: "Formulier — introzin met gekozen dienst",
    type: "textarea",
    help: "{dienst} wordt de naam van de gekozen dienst.",
  },
  { key: "formSubAlgemeen", label: "Formulier — introzin zonder dienst", type: "textarea" },
  { key: "formBedankt", label: "Formulier — kop na versturen", type: "text" },
  { key: "formKnopBezig", label: "Formulier — knop tijdens versturen", type: "text" },
  { key: "formKnopDatum", label: "Formulier — knop bij een dagdienst", type: "text" },
  { key: "formKnopKennismaking", label: "Formulier — knop bij een kennismaking", type: "text" },
  { key: "formKnopGesprek", label: "Formulier — knop zonder dienst", type: "text" },
  { key: "veldNaam", label: "Formulier — label naam", type: "text" },
  { key: "hintNaam", label: "Formulier — hint naam", type: "text" },
  { key: "veldEmail", label: "Formulier — label e-mailadres", type: "text" },
  { key: "hintEmail", label: "Formulier — hint e-mailadres", type: "text" },
  { key: "veldOrganisatie", label: "Formulier — label organisatie", type: "text" },
  { key: "veldOrganisatieBij", label: "Formulier — toevoeging bij organisatie", type: "text" },
  { key: "hintOrganisatie", label: "Formulier — hint organisatie", type: "text" },
  { key: "veldRol", label: "Formulier — label rol", type: "text" },
  { key: "veldRolBij", label: "Formulier — toevoeging bij rol", type: "text" },
  { key: "hintRol", label: "Formulier — hint rol", type: "text" },
  { key: "veldDienst", label: "Formulier — label dienstkeuze", type: "text" },
  { key: "optieKies", label: "Formulier — eerste optie in de dienstkeuze", type: "text" },
  { key: "optieWeetNiet", label: "Formulier — laatste optie in de dienstkeuze", type: "text" },
  { key: "veldGroep", label: "Formulier — label aantal deelnemers", type: "text" },
  { key: "veldGroepBij", label: "Formulier — toevoeging bij aantal deelnemers", type: "text" },
  { key: "hintGroep", label: "Formulier — hint aantal deelnemers", type: "text" },
  { key: "vragenKicker", label: "Formulier — kicker boven de vervolgvragen", type: "text" },
  { key: "veldSector", label: "Formulier — label sector", type: "text" },
  { key: "veldSectorBij", label: "Formulier — toevoeging bij sector", type: "text" },
  { key: "veldOnderwerp", label: "Formulier — label onderwerp", type: "text" },
  { key: "veldOnderwerpBij", label: "Formulier — toevoeging bij onderwerp", type: "text" },
  { key: "veldToelichting", label: "Formulier — label toelichting", type: "text" },
  { key: "veldToelichtingBij", label: "Formulier — toevoeging bij toelichting", type: "text" },
  { key: "hintToelichting", label: "Formulier — hint toelichting", type: "textarea" },
  { key: "privacyTekst", label: "Formulier — regel onder de knop", type: "textarea" },
  { key: "privacyLink", label: "Formulier — linktekst naar het privacybeleid", type: "text" },
  { key: "emailAdres", label: "Contactgegevens — e-mailadres", type: "text" },
  {
    key: "telefoonNummer",
    label: "Contactgegevens — telefoonnummer (voor de link)",
    type: "text",
    placeholder: "+31610751254",
    help: "Internationaal en zonder opmaak; hier hangen de bel- en WhatsApp-link aan.",
  },
  {
    key: "telefoonWeergave",
    label: "Contactgegevens — telefoonnummer (zoals getoond)",
    type: "text",
    placeholder: "06–10751254",
  },
] as const satisfies readonly FieldDef[];

/** Standaardtekst per veld: de startwaarde in de editor en de terugval op de site. */
export const TEKSTEN = {
  heroKicker: "Contact",
  linkedinLabel: "LinkedIn",
  linkedinKnop: "Volg ons op LinkedIn",
  casesKnop: "Bekijk klantverhalen",
  formTitel: "Plan een gesprek",
  formSubDienst:
    "Je vraag gaat over {dienst}. Vul je gegevens in, dan komen we binnen één werkdag met een voorstel terug.",
  formSubAlgemeen:
    "Vertel kort waar het over gaat; een korte vraag mag ook. Je krijgt binnen één werkdag antwoord van een echt mens.",
  formBedankt: "Bedankt!",
  formKnopBezig: "Versturen…",
  formKnopDatum: "Vraag een datum aan",
  formKnopKennismaking: "Plan de kennismaking",
  formKnopGesprek: "Plan het gesprek",
  veldNaam: "Naam",
  hintNaam: "Jouw naam",
  veldEmail: "Zakelijk e-mailadres",
  hintEmail: "naam@organisatie.nl",
  veldOrganisatie: "Organisatie",
  veldOrganisatieBij: "(optioneel)",
  hintOrganisatie: "Naam van je organisatie",
  veldRol: "Jouw rol",
  veldRolBij: "(optioneel)",
  hintRol: "Bijv. CIO, manager uitvoering",
  veldDienst: "Waar gaat het over?",
  optieKies: "Kies een dienst",
  optieWeetNiet: "Weet ik nog niet",
  veldGroep: "Aantal deelnemers",
  veldGroepBij: "(indicatie)",
  hintGroep: "Bijv. 8",
  vragenKicker: "Over deze dienst",
  veldSector: "In welke sector werk je?",
  veldSectorBij: "(optioneel)",
  veldOnderwerp: "Waar gaat je vraagstuk over?",
  veldOnderwerpBij: "(optioneel)",
  veldToelichting: "Toelichting",
  veldToelichtingBij: "(optioneel)",
  hintToelichting: "Wat speelt er? Een paar zinnen is genoeg.",
  privacyTekst:
    "We gebruiken je gegevens alleen om dit gesprek te plannen. Geen nieuwsbrief, geen belrondes. Zie ons",
  privacyLink: "privacybeleid",
  emailAdres: "hello@thenewwaveit.com",
  telefoonNummer: "+31610751254",
  telefoonWeergave: "06–10751254",
  heroTitleStart: "Waar kunnen we je ",
  heroAccent: "mee helpen",
  heroLead:
    "Een gesprek plannen kan, maar een korte vraag stellen mag ook gewoon. Bel, mail, app of kom langs, je zit nergens aan vast.",
  verwachtTitel: "Wat je kunt verwachten",
  verwacht1Titel: "Voorbereiding",
  verwacht1Tekst:
    "We verdiepen ons vooraf in jouw sector en organisatie, zodat het gesprek meteen de diepte in kan.",
  verwacht2Titel: "Het gesprek",
  verwacht2Tekst:
    "Laagdrempelig, met een van ons: gewoon kennismaken kan, direct de diepte in op jouw vraagstuk ook. Geen verkooppraatje.",
  verwacht3Titel: "Concreet vervolg",
  verwacht3Tekst: "Binnen drie dagen een eerste analyse met mogelijke routes, geheel vrijblijvend.",
  manierenKop: "Manieren om contact op te nemen",
  manier1Titel: "Bel ons direct",
  manier1Tekst: "Op werkdagen tussen 9 en 17 uur krijg je meteen iemand aan de lijn.",
  manier2Titel: "Stuur een mail",
  manier2Tekst: "Stel je vraag, hoe klein ook. Binnen één werkdag een reactie van een echt mens.",
  manier3Titel: "App met ons",
  manier3Tekst: "Liever appen? Stuur een berichtje via WhatsApp, we reageren snel.",
  manier3Knop: "Start een chat",
  manier4Titel: "Plan een gesprek",
  manier4Tekst:
    "Laagdrempelig, met een van ons: gewoon kennismaken kan, direct de diepte in op jouw vraagstuk ook. Vrijblijvend en zonder verkooppraatje.",
  manier4Knop: "Plan het gesprek",
  expertKop: "Je spreekt met o.a.",
  adresTitel: "Bezoekadres",
  adresRegel: "Ganzenmarkt 6, Utrecht. Koffie staat klaar",
  ctaTitel: "Liever eerst zien wat we voor anderen deden?",
} satisfies Record<(typeof VELDEN)[number]["key"], string>;
