import type { FieldDef } from "../schema";

/** De velden die de editor voor deze pagina toont. */
export const VELDEN = [
  { key: "kennismakenLink", label: "Hero — link naar kennismaken", type: "text" },
  { key: "subnavLabel", label: "Subnavigatie — voorleeslabel", type: "text" },
  { key: "overKicker", label: "Over deze dienst — kicker", type: "text" },
  {
    key: "overTitel",
    label: "Over deze dienst — titel",
    type: "text",
    help: "{naam} wordt de dienstnaam.",
  },
  { key: "voorWieKicker", label: "Voor wie — kicker", type: "text" },
  { key: "herkenKicker", label: "Herken je dit — kicker", type: "text" },
  { key: "herkenTitel", label: "Herken je dit — titel", type: "text" },
  { key: "meeneemtKicker", label: "Wat je meeneemt — kicker", type: "text" },
  { key: "voorbereidingKicker", label: "Voorbereiding — kicker", type: "text" },
  { key: "voorbereidingTitel", label: "Voorbereiding — titel", type: "text" },
  { key: "wijZorgenTitel", label: "Voorbereiding — kolom wij", type: "text" },
  { key: "jijZorgtTitel", label: "Voorbereiding — kolom jij", type: "text" },
  { key: "daarnaKicker", label: "Daarna — kicker", type: "text" },
  { key: "daarnaTitel", label: "Daarna — titel", type: "text" },
  { key: "faqKicker", label: "Veelgestelde vragen — kicker", type: "text" },
  { key: "catalogusKicker", label: "Rest van de catalogus — kicker", type: "text" },
  { key: "catalogusTitel", label: "Rest van de catalogus — titel", type: "text" },
  { key: "catalogusAlle", label: "Rest van de catalogus — link", type: "text" },
  { key: "pijlersKicker", label: "Wat we doen — kicker", type: "text" },
  {
    key: "pijlersTitel",
    label: "Wat we doen — titel",
    type: "text",
    help: "{naam} wordt de richting.",
  },
  { key: "aanpakKicker", label: "Onze aanpak — kicker", type: "text" },
  { key: "aanpakTitel", label: "Onze aanpak — titel", type: "text" },
  { key: "vraagstukkenKicker", label: "Vraagstukken — kicker", type: "text" },
  { key: "vraagstukkenTitel", label: "Vraagstukken — titel", type: "text" },
  { key: "welNietKicker", label: "Wel of niet — kicker", type: "text" },
  { key: "welTitel", label: "Wel of niet — kolom wel", type: "text" },
  { key: "nietTitel", label: "Wel of niet — kolom niet", type: "text" },
  { key: "waaromKicker", label: "Waarom wij — kicker", type: "text" },
  { key: "waaromTitel", label: "Waarom wij — titel", type: "text" },
  { key: "expertMail", label: "Waarom wij — mail-link bij een expert", type: "text" },
  { key: "expertLinkedin", label: "Waarom wij — LinkedIn-link bij een expert", type: "text" },
  { key: "partnersTitel", label: "Technologiepartners — titel", type: "text" },
  {
    key: "outcomesKicker",
    label: "Wat het oplevert — kicker",
    type: "text",
    help: "{naam} wordt de dienstnaam.",
  },
  { key: "outcomesTitel", label: "Wat het oplevert — titel", type: "text" },
  { key: "caseKicker", label: "Klantverhaal — kicker", type: "text" },
  { key: "caseLink", label: "Klantverhaal — link", type: "text" },
  { key: "sectorenKicker", label: "Sectoren — kicker", type: "text" },
  { key: "sectorenTitel", label: "Sectoren — titel", type: "text" },
  { key: "inzichtenKicker", label: "Inzichten — kicker", type: "text" },
  { key: "inzichtenAlle", label: "Inzichten — link naar het overzicht", type: "text" },
  { key: "inzichtenMeer", label: "Inzichten — link per artikel", type: "text" },
  { key: "kaartMeeneemt", label: "Dienstkaart — kop boven de bullets", type: "text" },
  { key: "kaartMeer", label: "Dienstkaart — link", type: "text" },
  { key: "stappenplanLink", label: "Fasen — link naar het stappenplan", type: "text" },
  { key: "instapChip", label: "Route — chip bij de instapdienst", type: "text" },
  { key: "routeKicker", label: "Route — kicker", type: "text" },
  { key: "routeTitel", label: "Route — titel", type: "text" },
  { key: "routeVoet", label: "Route — regel onder de stappen", type: "textarea" },
  { key: "routeKnop", label: "Route — knoptekst", type: "text" },
] as const satisfies readonly FieldDef[];

/** Standaardtekst per veld: de startwaarde in de editor en de terugval op de site. */
export const TEKSTEN = {
  kennismakenLink: "Liever eerst 20 min kennismaken →",
  subnavLabel: "Op deze pagina",
  overKicker: "Over deze dienst",
  overTitel: "Wat {naam} inhoudt",
  voorWieKicker: "Voor wie",
  herkenKicker: "Voor wie",
  herkenTitel: "Herken je dit?",
  meeneemtKicker: "Wat je meeneemt",
  voorbereidingKicker: "Voorbereiding",
  voorbereidingTitel: "Wat wij regelen, wat jij regelt",
  wijZorgenTitel: "Wij zorgen voor",
  jijZorgtTitel: "Jij zorgt voor",
  daarnaKicker: "Daarna",
  daarnaTitel: "Wat er logisch op volgt",
  faqKicker: "Veelgestelde vragen",
  catalogusKicker: "Diensten",
  catalogusTitel: "De rest van de catalogus",
  catalogusAlle: "Alle diensten",
  pijlersKicker: "Wat we doen",
  pijlersTitel: "Onze {naam}-diensten",
  aanpakKicker: "Onze aanpak",
  aanpakTitel: "Zo pakken we het aan",
  vraagstukkenKicker: "Wanneer zet je dit in",
  vraagstukkenTitel: "Hiervoor komen organisaties bij ons",
  welNietKicker: "Eerlijk over de grenzen",
  welTitel: "Dit past als…",
  nietTitel: "Dit past niet als…",
  waaromKicker: "Waarom The New Wave IT",
  waaromTitel: "De juiste partner voor jouw traject",
  expertMail: "Mail",
  expertLinkedin: "LinkedIn",
  partnersTitel: "Technologiepartners",
  outcomesKicker: "Resultaten met {naam}",
  outcomesTitel: "Wat het oplevert",
  caseKicker: "Klantverhaal",
  caseLink: "Lees het volledige verhaal →",
  sectorenKicker: "In welke sectoren",
  sectorenTitel: "Waar dit het meest speelt",
  inzichtenKicker: "Inzichten",
  inzichtenAlle: "Alle inzichten",
  inzichtenMeer: "Lees meer",
  kaartMeeneemt: "Wat je meeneemt",
  kaartMeer: "Meer over deze dienst",
  stappenplanLink: "Bekijk het volledige stappenplan",
  instapChip: "Lichte instap",
  routeKicker: "Jouw route",
  routeTitel: "Begin bij de instap, schaal op wanneer het werkt.",
  routeVoet: "Elke stap is los te boeken. Je hoeft dus niet vooraf te kiezen hoe ver je wilt gaan.",
  routeKnop: "Begin hier",
} satisfies Record<(typeof VELDEN)[number]["key"], string>;
