import type { FieldDef } from "../schema";

/** De velden die de editor voor deze pagina toont. */
export const VELDEN = [
  { key: "solKnop", label: "Sollicitatieformulier — knoptekst", type: "text" },
  { key: "solKnopBezig", label: "Sollicitatieformulier — knop tijdens versturen", type: "text" },
  { key: "solBedankt", label: "Sollicitatieformulier — kop na versturen", type: "text" },
  { key: "solVeldNaam", label: "Sollicitatieformulier — label naam", type: "text" },
  { key: "solHintNaam", label: "Sollicitatieformulier — hint naam", type: "text" },
  { key: "solVeldEmail", label: "Sollicitatieformulier — label e-mailadres", type: "text" },
  { key: "solHintEmail", label: "Sollicitatieformulier — hint e-mailadres", type: "text" },
  { key: "solVeldTelefoon", label: "Sollicitatieformulier — label telefoon", type: "text" },
  { key: "solHintTelefoon", label: "Sollicitatieformulier — hint telefoon", type: "text" },
  {
    key: "solVeldMotivatieBestand",
    label: "Sollicitatieformulier — label motivatiebrief",
    type: "text",
  },
  {
    key: "solBijMotivatieBestand",
    label: "Sollicitatieformulier — toevoeging motivatiebestand",
    type: "text",
  },
  { key: "solVeldCv", label: "Sollicitatieformulier — label cv", type: "text" },
  { key: "solBijCv", label: "Sollicitatieformulier — toevoeging cv", type: "text" },
  {
    key: "solVeldLink",
    label: "Sollicitatieformulier — label LinkedIn of portfolio",
    type: "text",
  },
  {
    key: "solBijLink",
    label: "Sollicitatieformulier — toevoeging LinkedIn of portfolio",
    type: "text",
  },
  {
    key: "solHintLink",
    label: "Sollicitatieformulier — hint LinkedIn of portfolio",
    type: "text",
  },
  {
    key: "solLinkUitleg",
    label: "Sollicitatieformulier — uitleg onder LinkedIn",
    type: "textarea",
  },
  {
    key: "solOptioneel",
    label: "Sollicitatieformulier — woord voor een optioneel veld",
    type: "text",
  },
  {
    key: "solPrivacyTekst",
    label: "Sollicitatieformulier — regel onder de knop",
    type: "textarea",
  },
  {
    key: "solPrivacyLink",
    label: "Sollicitatieformulier — linktekst privacybeleid",
    type: "text",
  },
  { key: "knopSolliciteer", label: "Hero — eerste knop", type: "text" },
  { key: "knopWerkenBij", label: "Hero — tweede knop", type: "text" },
  { key: "recruiterRol", label: "Recruiter — rol", type: "text" },
  { key: "recruiterMail", label: "Recruiter — link naar de mail", type: "text" },
  { key: "labelTeam", label: "Kenmerken — label team", type: "text" },
  { key: "labelNiveau", label: "Kenmerken — label niveau", type: "text" },
  { key: "labelLocatie", label: "Kenmerken — label locatie", type: "text" },
  { key: "labelUren", label: "Kenmerken — label uren", type: "text" },
  { key: "labelSalaris", label: "Kenmerken — label salaris", type: "text" },
  { key: "procedureKicker", label: "Procedure — kicker", type: "text" },
  { key: "procedureTitel", label: "Procedure — titel", type: "text" },
  { key: "andereKicker", label: "Andere vacatures — kicker", type: "text" },
  { key: "andereTitel", label: "Andere vacatures — titel", type: "text" },
] as const satisfies readonly FieldDef[];

/** Standaardtekst per veld: de startwaarde in de editor en de terugval op de site. */
export const TEKSTEN = {
  solKnop: "Verstuur sollicitatie",
  solKnopBezig: "Versturen…",
  solBedankt: "Bedankt voor je sollicitatie!",
  solVeldNaam: "Naam",
  solHintNaam: "Jouw naam",
  solVeldEmail: "E-mailadres",
  solHintEmail: "naam@voorbeeld.nl",
  solVeldTelefoon: "Telefoon",
  solHintTelefoon: "06–12345678",
  solVeldMotivatieBestand: "Motivatiebrief",
  solBijMotivatieBestand: "(pdf of Word)",
  solVeldCv: "Je cv",
  solBijCv: "(pdf of Word, max. 8 MB)",
  solVeldLink: "LinkedIn of portfolio",
  solBijLink: "(optioneel)",
  solHintLink: "linkedin.com/in/jouwnaam",
  solLinkUitleg: "Geen cv bij de hand? Je LinkedIn of portfolio is net zo goed.",
  solOptioneel: "(optioneel)",
  solPrivacyTekst: "We gebruiken je gegevens alleen voor deze sollicitatie. Zie ons",
  solPrivacyLink: "privacybeleid",
  knopSolliciteer: "Solliciteer direct",
  knopWerkenBij: "Ontdek werken bij",
  recruiterRol: "Recruiter",
  recruiterMail: "Mail",
  labelTeam: "Team",
  labelNiveau: "Niveau",
  labelLocatie: "Locatie",
  labelUren: "Uren",
  labelSalaris: "Salaris",
  procedureKicker: "Zo solliciteer je",
  procedureTitel: "Vier stappen, twee weken",
  andereKicker: "Andere vacatures",
  andereTitel: "Ook op zoek naar…",
} satisfies Record<(typeof VELDEN)[number]["key"], string>;
