import type { ComponentType } from "react";
import {
  AlertTriangle,
  AppWindow,
  Ban,
  BookOpen,
  Bot,
  Calculator,
  Check,
  ClipboardCheck,
  Compass,
  Flag,
  FolderDown,
  GitBranch,
  GitFork,
  GraduationCap,
  Handshake,
  HardHat,
  Layers,
  LayoutGrid,
  ListChecks,
  ListOrdered,
  Map,
  MessageSquareWarning,
  Presentation,
  RefreshCw,
  Route,
  Scale,
  ScanSearch,
  Shield,
  ShieldCheck,
  Target,
  Telescope,
  UserCheck,
  Users,
} from "lucide-react";

/**
 * De lucide-iconen die een "wat je meeneemt"-regel mag gebruiken. De namen
 * komen uit de ontwerpen in Claude Design; een naam die hier ontbreekt valt
 * stil terug op een vinkje. `tests/unit/diensten-detail.spec.ts` bewaakt dat.
 *
 * Los van page.tsx zodat de test de map kan importeren zonder de pagina
 * (met `use cache` en Next-only imports) mee te trekken.
 */
export const ICONEN: Record<string, ComponentType> = {
  "alert-triangle": AlertTriangle,
  "app-window": AppWindow,
  ban: Ban,
  "book-open": BookOpen,
  bot: Bot,
  calculator: Calculator,
  check: Check,
  "clipboard-check": ClipboardCheck,
  compass: Compass,
  flag: Flag,
  "folder-down": FolderDown,
  "git-branch": GitBranch,
  "git-fork": GitFork,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  "hard-hat": HardHat,
  layers: Layers,
  "layout-grid": LayoutGrid,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  map: Map,
  "message-square-warning": MessageSquareWarning,
  presentation: Presentation,
  "refresh-cw": RefreshCw,
  route: Route,
  scale: Scale,
  "scan-search": ScanSearch,
  shield: Shield,
  "shield-check": ShieldCheck,
  target: Target,
  telescope: Telescope,
  "user-check": UserCheck,
  users: Users,
};
