-- Weessleutels in cms_paginas -- stap 3 van 3: controle
--
-- De home-rij had 23 sleutels terwijl het schema er 10 kent. Die dertien
-- stonden nooit in PAGE_FIELDS; ze komen uit een ontwerp van vóór de velden die
-- we eerder verwijderden. Ze doen niets -- geen pagina leest ze, de editor
-- toont ze niet -- maar ze staan er wel.
--
-- Deze drift is niet met een unittest te vangen: tests/unit/cms-pages.spec.ts
-- vergelijkt code met schema, en de database zit daar niet bij.
--
-- De sleutellijst is gegenereerd uit PAGE_FIELDS (154 sleutels).
-- Regenereer hem als het schema wijzigt, anders ruimt stap 2 iets op dat wél
-- gebruikt wordt.

-- in_database en in_schema horen op elke regel gelijk te zijn.

with schema_sleutels (slug, sleutel) as (
  values
    ('contact', 'heroTitleStart'),
    ('contact', 'heroAccent'),
    ('contact', 'heroLead'),
    ('contact', 'verwachtTitel'),
    ('contact', 'verwacht1Titel'),
    ('contact', 'verwacht1Tekst'),
    ('contact', 'verwacht2Titel'),
    ('contact', 'verwacht2Tekst'),
    ('contact', 'verwacht3Titel'),
    ('contact', 'verwacht3Tekst'),
    ('contact', 'ctaTitel'),
    ('diensten', 'heroTitleStart'),
    ('diensten', 'heroAccent'),
    ('diensten', 'heroTitleEnd'),
    ('diensten', 'heroLead'),
    ('diensten', 'basisKicker'),
    ('diensten', 'basisTitel'),
    ('diensten', 'basisTekst'),
    ('diensten', 'basisRol1Label'),
    ('diensten', 'basisRol1Naam'),
    ('diensten', 'basisRol1Tekst'),
    ('diensten', 'basisRol2Label'),
    ('diensten', 'basisRol2Naam'),
    ('diensten', 'basisRol2Tekst'),
    ('diensten', 'basisRol3Label'),
    ('diensten', 'basisRol3Naam'),
    ('diensten', 'basisRol3Tekst'),
    ('diensten', 'basisRol4Label'),
    ('diensten', 'basisRol4Naam'),
    ('diensten', 'basisRol4Tekst'),
    ('diensten', 'basisPersoonRol'),
    ('diensten', 'basisPersoonTekst'),
    ('diensten', 'basisInzetLabel'),
    ('diensten', 'basisInzetWaarde'),
    ('diensten', 'basisPunt1'),
    ('diensten', 'basisPunt2'),
    ('diensten', 'basisPunt3'),
    ('diensten', 'basisPunt4'),
    ('diensten', 'basisCta'),
    ('diensten', 'basisCtaAlt'),
    ('diensten', 'instapKicker'),
    ('diensten', 'instapTitel'),
    ('diensten', 'instapIntro'),
    ('diensten', 'verdiepingKicker'),
    ('diensten', 'verdiepingTitel'),
    ('diensten', 'verdiepingIntro'),
    ('diensten', 'verdiepingRichtingTekst'),
    ('diensten', 'verdiepingCapaciteitTekst'),
    ('diensten', 'fase1Titel'),
    ('diensten', 'fase1Tekst'),
    ('diensten', 'fase2Titel'),
    ('diensten', 'fase2Tekst'),
    ('diensten', 'fase3Titel'),
    ('diensten', 'fase3Tekst'),
    ('diensten', 'fase4Titel'),
    ('diensten', 'fase4Tekst'),
    ('diensten', 'fase5Titel'),
    ('diensten', 'fase5Tekst'),
    ('diensten', 'ctaTitel'),
    ('diensten-ai', 'metaTitle'),
    ('diensten-ai', 'metaDescription'),
    ('diensten-ai', 'badgeLabel'),
    ('diensten-ai', 'heroTitleStart'),
    ('diensten-ai', 'heroLead'),
    ('diensten-ai', 'crossrefTitel'),
    ('diensten-ai', 'ctaTitel'),
    ('diensten-mendix', 'metaTitle'),
    ('diensten-mendix', 'metaDescription'),
    ('diensten-mendix', 'badgeLabel'),
    ('diensten-mendix', 'heroTitleStart'),
    ('diensten-mendix', 'heroLead'),
    ('diensten-mendix', 'crossrefTitel'),
    ('diensten-mendix', 'ctaTitel'),
    ('diensten-strategie', 'metaTitle'),
    ('diensten-strategie', 'metaDescription'),
    ('diensten-strategie', 'badgeLabel'),
    ('diensten-strategie', 'heroTitleStart'),
    ('diensten-strategie', 'heroLead'),
    ('diensten-strategie', 'instapTitel'),
    ('diensten-strategie', 'instapTekst'),
    ('diensten-strategie', 'instapKnop'),
    ('diensten-strategie', 'crossrefTitel'),
    ('diensten-strategie', 'ctaTitel'),
    ('home', 'heroTitleStart'),
    ('home', 'heroAccent'),
    ('home', 'heroLead'),
    ('home', 'ctaTitel'),
    ('home', 'ctaKnop'),
    ('home', 'waaromTitel'),
    ('home', 'mensenKicker'),
    ('home', 'mensenTitel'),
    ('home', 'mensenP1'),
    ('home', 'mensenP2'),
    ('over-ons', 'heroTitleStart'),
    ('over-ons', 'heroAccent'),
    ('over-ons', 'heroLead'),
    ('over-ons', 'missieTitel'),
    ('over-ons', 'missieP1'),
    ('over-ons', 'missieP2'),
    ('over-ons', 'teamTitel'),
    ('over-ons', 'teamP1'),
    ('over-ons', 'teamP2'),
    ('over-ons', 'ctaTitel'),
    ('over-ons', 'waardenKicker'),
    ('over-ons', 'waardenTitel'),
    ('over-ons', 'waarde1Titel'),
    ('over-ons', 'waarde1Tekst'),
    ('over-ons', 'waarde2Titel'),
    ('over-ons', 'waarde2Tekst'),
    ('over-ons', 'waarde3Titel'),
    ('over-ons', 'waarde3Tekst'),
    ('over-ons', 'waarde4Titel'),
    ('over-ons', 'waarde4Tekst'),
    ('sectoren', 'heroTitleStart'),
    ('sectoren', 'heroAccent'),
    ('sectoren', 'heroLead'),
    ('sectoren', 'werkwijzeKicker'),
    ('sectoren', 'werkwijzeTitel'),
    ('sectoren', 'wijze1Titel'),
    ('sectoren', 'wijze1Tekst'),
    ('sectoren', 'wijze2Titel'),
    ('sectoren', 'wijze2Tekst'),
    ('sectoren', 'wijze3Titel'),
    ('sectoren', 'wijze3Tekst'),
    ('sectoren', 'ctaTitel'),
    ('werken-bij', 'heroTitleStart'),
    ('werken-bij', 'heroAccent'),
    ('werken-bij', 'heroLead'),
    ('werken-bij', 'groeiKicker'),
    ('werken-bij', 'groeiTitel'),
    ('werken-bij', 'groeiIntro'),
    ('werken-bij', 'groei1Titel'),
    ('werken-bij', 'groei1Tekst'),
    ('werken-bij', 'groei2Titel'),
    ('werken-bij', 'groei2Tekst'),
    ('werken-bij', 'groei3Titel'),
    ('werken-bij', 'groei3Tekst'),
    ('werken-bij', 'tpKicker'),
    ('werken-bij', 'tpTitel'),
    ('werken-bij', 'tpIntro'),
    ('werken-bij', 'tp1Titel'),
    ('werken-bij', 'tp1Tekst'),
    ('werken-bij', 'tp2Titel'),
    ('werken-bij', 'tp2Tekst'),
    ('werken-bij', 'tp3Titel'),
    ('werken-bij', 'tp3Tekst'),
    ('werken-bij', 'cultuurKicker'),
    ('werken-bij', 'cultuurTitel'),
    ('werken-bij', 'cultuurP'),
    ('werken-bij', 'cultuur1'),
    ('werken-bij', 'cultuur2'),
    ('werken-bij', 'cultuur3'),
    ('werken-bij', 'cultuur4'),
    ('werken-bij', 'ctaTitel')
)
select p.slug,
       (select count(*) from jsonb_object_keys(p.data))               as in_database,
       (select count(*) from schema_sleutels s where s.slug = p.slug) as in_schema
  from cms_paginas p
 order by p.slug;
