-- Waar is het CMS dunner dan het schema? (14 september 2026)
--
-- Aanleiding: alle vijf de sectorrijen bleken `hook`, `pitch` en `kpiLabel` te
-- missen. Die velden zijn later aan het schema toegevoegd dan de rijen zijn
-- ingeladen, dus ze hebben er nooit in gestaan. De site klopt wel, want
-- `leesRijen` vult zo'n veld aan uit de seed, maar dat gebeurt met een
-- console.error per render en in de admin ziet een redacteur een leeg veld.
--
-- Deze query zoekt dezelfde situatie in alle acht de contenttypen plus de
-- paginateksten. Eén regel per rij, met hoeveel velden er ontbreken en welke.
-- Geen regels terug betekent: het CMS is overal even volledig als het schema.
--
-- De verwachte veldnamen komen uit FIELD_SCHEMAS en PAGE_FIELDS; deze query is
-- gegenereerd, niet met de hand bijgehouden.

with rijen as (
  select 'artikelen' as soort, slug, data from public.cms_artikelen
  union all select 'cases' as soort, slug, data from public.cms_cases
  union all select 'vacatures' as soort, slug, data from public.cms_vacatures
  union all select 'diensten' as soort, slug, data from public.cms_diensten
  union all select 'sectoren' as soort, slug, data from public.cms_sectoren
  union all select 'teamleden' as soort, slug, data from public.cms_teamleden
  union all select 'proposities' as soort, slug, data from public.cms_proposities
  union all select 'services' as soort, slug, data from public.cms_services
),
verwacht (soort, veld) as (values
    ('artikelen', 'discipline'),
    ('artikelen', 'sector'),
    ('artikelen', 'samenvatting'),
    ('artikelen', 'cover'),
    ('artikelen', 'leestijd'),
    ('artikelen', 'auteur'),
    ('artikelen', 'datum'),
    ('artikelen', 'inhoud'),
    ('cases', 'sector'),
    ('cases', 'metric'),
    ('cases', 'cardTitel'),
    ('cases', 'org'),
    ('cases', 'image'),
    ('cases', 'tag'),
    ('cases', 'h1'),
    ('cases', 'intro'),
    ('cases', 'challenge'),
    ('cases', 'pull'),
    ('cases', 'ketenTitel'),
    ('cases', 'ketenStappen'),
    ('cases', 'ketenSynthese'),
    ('cases', 'secties'),
    ('cases', 'resultaat'),
    ('cases', 'eindresultaten'),
    ('cases', 'quote'),
    ('cases', 'quoteNaam'),
    ('cases', 'quoteRol'),
    ('cases', 'impact'),
    ('cases', 'aside'),
    ('vacatures', 'functietitel'),
    ('vacatures', 'discipline'),
    ('vacatures', 'locatie'),
    ('vacatures', 'intro'),
    ('vacatures', 'employmentType'),
    ('vacatures', 'gepubliceerdOp'),
    ('vacatures', 'tags'),
    ('vacatures', 'secties'),
    ('vacatures', 'facts'),
    ('diensten', 'naam'),
    ('diensten', 'badgeIcon'),
    ('diensten', 'badgeLabel'),
    ('diensten', 'h1'),
    ('diensten', 'intro'),
    ('diensten', 'ctaSecondary'),
    ('diensten', 'kpis'),
    ('diensten', 'vraagstukken'),
    ('diensten', 'pijlersIntro'),
    ('diensten', 'pijlers'),
    ('diensten', 'aanpak'),
    ('diensten', 'waarom'),
    ('diensten', 'expertsHead'),
    ('diensten', 'experts'),
    ('diensten', 'partners'),
    ('diensten', 'outcomes'),
    ('diensten', 'caseTitle'),
    ('diensten', 'caseSector'),
    ('diensten', 'caseQuote'),
    ('diensten', 'caseNaam'),
    ('diensten', 'caseRol'),
    ('diensten', 'caseImage'),
    ('diensten', 'caseHref'),
    ('diensten', 'waarborg'),
    ('diensten', 'heroTheme'),
    ('diensten', 'serviceSlug'),
    ('diensten', 'insightsTitle'),
    ('diensten', 'insights'),
    ('diensten', 'ctaTitle'),
    ('diensten', 'sectoren'),
    ('diensten', 'welNietTitel'),
    ('diensten', 'welWanneer'),
    ('diensten', 'nietWanneer'),
    ('sectoren', 'naam'),
    ('sectoren', 'icon'),
    ('sectoren', 'heroTheme'),
    ('sectoren', 'metaTitle'),
    ('sectoren', 'metaDescription'),
    ('sectoren', 'hook'),
    ('sectoren', 'pitch'),
    ('sectoren', 'kpiLabel'),
    ('sectoren', 'h1'),
    ('sectoren', 'intro'),
    ('sectoren', 'herkenningTitel'),
    ('sectoren', 'herkenning'),
    ('sectoren', 'mensenTitel'),
    ('sectoren', 'mensenTekst'),
    ('sectoren', 'mensenFoto'),
    ('sectoren', 'mensenFotoPositie'),
    ('sectoren', 'mensenTags'),
    ('sectoren', 'waaromTitel'),
    ('sectoren', 'waaromAlineas'),
    ('sectoren', 'waaromFoto'),
    ('sectoren', 'waaromFotoPositie'),
    ('sectoren', 'quote'),
    ('sectoren', 'quoteTeamlid'),
    ('sectoren', 'oplossingenTitel'),
    ('sectoren', 'oplossingenIntro'),
    ('sectoren', 'oplossingen'),
    ('sectoren', 'bouwenTitel'),
    ('sectoren', 'useCases'),
    ('sectoren', 'aanpakTitel'),
    ('sectoren', 'aanpakFoto'),
    ('sectoren', 'aanpakFotoPositie'),
    ('sectoren', 'stappen'),
    ('sectoren', 'belofte'),
    ('sectoren', 'dienstenTitel'),
    ('sectoren', 'dienstLinks'),
    ('sectoren', 'faqTitel'),
    ('sectoren', 'faq'),
    ('sectoren', 'teamTitel'),
    ('sectoren', 'team'),
    ('sectoren', 'ctaTitel'),
    ('sectoren', 'ctaTekst'),
    ('sectoren', 'ctaTeamlid'),
    ('sectoren', 'ctaTeamlidTekst'),
    ('teamleden', 'rol'),
    ('teamleden', 'foto'),
    ('teamleden', 'contactrol'),
    ('teamleden', 'telefoon'),
    ('teamleden', 'email'),
    ('teamleden', 'linkedin'),
    ('teamleden', 'bio'),
    ('proposities', 'nummer'),
    ('proposities', 'belofte'),
    ('proposities', 'wat'),
    ('proposities', 'hoe'),
    ('proposities', 'onderscheid'),
    ('proposities', 'solutions'),
    ('services', 'naam'),
    ('services', 'familie'),
    ('services', 'richting'),
    ('services', 'hubTier'),
    ('services', 'ookRelevantVoor'),
    ('services', 'fase'),
    ('services', 'pitch'),
    ('services', 'beschrijving'),
    ('services', 'doelgroep'),
    ('services', 'duur'),
    ('services', 'groepsgrootte'),
    ('services', 'prijzen'),
    ('services', 'resultaten'),
    ('services', 'volgendeStap'),
    ('services', 'volgendeStapSlugs'),
    ('services', 'ctaLabel'),
    ('services', 'ctaType'),
    ('services', 'kpis'),
    ('services', 'vraagstukken'),
    ('services', 'aanpak'),
    ('services', 'waarom'),
    ('services', 'outcomes'),
    ('services', 'caseTitle'),
    ('services', 'caseSector'),
    ('services', 'caseQuote'),
    ('services', 'caseNaam'),
    ('services', 'caseRol'),
    ('services', 'caseImage'),
    ('services', 'caseHref'),
    ('services', 'kop'),
    ('services', 'lead'),
    ('services', 'feiten'),
    ('services', 'prijsToelichting'),
    ('services', 'boekPunten'),
    ('services', 'herkenIntro'),
    ('services', 'herken'),
    ('services', 'meeneemtTitel'),
    ('services', 'meeneemt'),
    ('services', 'meeneemtFoto'),
    ('services', 'dagLabel'),
    ('services', 'dagTitel'),
    ('services', 'dagIntro'),
    ('services', 'dagSlots'),
    ('services', 'voorbereidingIntro'),
    ('services', 'wijZorgen'),
    ('services', 'jijZorgt'),
    ('services', 'daarnaIntro'),
    ('services', 'vervolg'),
    ('services', 'faqTitel'),
    ('services', 'faq'),
    ('services', 'ctaTitel')
),
paginarijen as (
  select slug, data from public.cms_paginas
),
paginaverwacht (slug, veld) as (values
    ('home', 'heroTitleStart'),
    ('home', 'heroAccent'),
    ('home', 'heroTitleEnd'),
    ('home', 'heroLead'),
    ('home', 'ctaTitel'),
    ('home', 'ctaKnop'),
    ('home', 'mensenKicker'),
    ('home', 'mensenTitel'),
    ('home', 'mensenP1'),
    ('home', 'mensenP2'),
    ('home', 'dienstenKicker'),
    ('home', 'dienstenTitel'),
    ('home', 'dienstenIntro'),
    ('home', 'sectorenKicker'),
    ('home', 'sectorenTitel'),
    ('home', 'sectorenIntro'),
    ('home', 'casesKicker'),
    ('home', 'casesTitel'),
    ('home', 'inzichtenKicker'),
    ('home', 'inzichtenTitel'),
    ('over-ons', 'heroTitleStart'),
    ('over-ons', 'heroAccent'),
    ('over-ons', 'heroLead'),
    ('over-ons', 'missieTitel'),
    ('over-ons', 'missieP1'),
    ('over-ons', 'missieP2'),
    ('over-ons', 'teamTitel'),
    ('over-ons', 'teamP1'),
    ('over-ons', 'teamP2'),
    ('over-ons', 'ctaTitel'),
    ('over-ons', 'waardenKicker'),
    ('over-ons', 'waardenTitel'),
    ('over-ons', 'waarde1Titel'),
    ('over-ons', 'waarde1Tekst'),
    ('over-ons', 'waarde2Titel'),
    ('over-ons', 'waarde2Tekst'),
    ('over-ons', 'waarde3Titel'),
    ('over-ons', 'waarde3Tekst'),
    ('over-ons', 'waarde4Titel'),
    ('over-ons', 'kpi1Getal'),
    ('over-ons', 'kpi1Label'),
    ('over-ons', 'kpi2Getal'),
    ('over-ons', 'kpi2Label'),
    ('over-ons', 'kpi3Getal'),
    ('over-ons', 'kpi3Label'),
    ('over-ons', 'missieFotoAlt'),
    ('over-ons', 'teamFotoAlt'),
    ('over-ons', 'adresRegel'),
    ('over-ons', 'waarde4Tekst'),
    ('contact', 'heroTitleStart'),
    ('contact', 'heroAccent'),
    ('contact', 'heroLead'),
    ('contact', 'verwachtTitel'),
    ('contact', 'verwacht1Titel'),
    ('contact', 'verwacht1Tekst'),
    ('contact', 'verwacht2Titel'),
    ('contact', 'verwacht2Tekst'),
    ('contact', 'verwacht3Titel'),
    ('contact', 'verwacht3Tekst'),
    ('contact', 'manierenKop'),
    ('contact', 'manier1Titel'),
    ('contact', 'manier1Tekst'),
    ('contact', 'manier2Titel'),
    ('contact', 'manier2Tekst'),
    ('contact', 'manier3Titel'),
    ('contact', 'manier3Tekst'),
    ('contact', 'manier3Knop'),
    ('contact', 'manier4Titel'),
    ('contact', 'manier4Tekst'),
    ('contact', 'manier4Knop'),
    ('contact', 'expertKop'),
    ('contact', 'adresTitel'),
    ('contact', 'adresRegel'),
    ('contact', 'ctaTitel'),
    ('diensten', 'heroTitleStart'),
    ('diensten', 'heroAccent'),
    ('diensten', 'heroTitleEnd'),
    ('diensten', 'heroLead'),
    ('diensten', 'basisKicker'),
    ('diensten', 'basisTitel'),
    ('diensten', 'basisTekst'),
    ('diensten', 'basisRol1Label'),
    ('diensten', 'basisRol1Naam'),
    ('diensten', 'basisRol1Tekst'),
    ('diensten', 'basisRol2Label'),
    ('diensten', 'basisRol2Naam'),
    ('diensten', 'basisRol2Tekst'),
    ('diensten', 'basisRol3Label'),
    ('diensten', 'basisRol3Naam'),
    ('diensten', 'basisRol3Tekst'),
    ('diensten', 'basisRol4Label'),
    ('diensten', 'basisRol4Naam'),
    ('diensten', 'basisRol4Tekst'),
    ('diensten', 'basisPersoonRol'),
    ('diensten', 'basisPersoonTekst'),
    ('diensten', 'basisInzetLabel'),
    ('diensten', 'basisInzetWaarde'),
    ('diensten', 'basisPunt1'),
    ('diensten', 'basisPunt2'),
    ('diensten', 'basisPunt3'),
    ('diensten', 'basisPunt4'),
    ('diensten', 'basisCta'),
    ('diensten', 'basisCtaAlt'),
    ('diensten', 'instapKicker'),
    ('diensten', 'instapTitel'),
    ('diensten', 'instapIntro'),
    ('diensten', 'verdiepingKicker'),
    ('diensten', 'verdiepingTitel'),
    ('diensten', 'verdiepingIntro'),
    ('diensten', 'verdiepingRichtingTekst'),
    ('diensten', 'verdiepingCapaciteitTekst'),
    ('diensten', 'fase1Titel'),
    ('diensten', 'fase1Tekst'),
    ('diensten', 'fase2Titel'),
    ('diensten', 'fase2Tekst'),
    ('diensten', 'fase3Titel'),
    ('diensten', 'fase3Tekst'),
    ('diensten', 'fase4Titel'),
    ('diensten', 'fase4Tekst'),
    ('diensten', 'fase5Titel'),
    ('diensten', 'fase5Tekst'),
    ('diensten', 'ctaTitel'),
    ('diensten-mendix', 'metaTitle'),
    ('diensten-mendix', 'metaDescription'),
    ('diensten-mendix', 'badgeLabel'),
    ('diensten-mendix', 'heroTitleStart'),
    ('diensten-mendix', 'heroLead'),
    ('diensten-mendix', 'crossrefTitel'),
    ('diensten-mendix', 'ctaTitel'),
    ('diensten-ai', 'metaTitle'),
    ('diensten-ai', 'metaDescription'),
    ('diensten-ai', 'badgeLabel'),
    ('diensten-ai', 'heroTitleStart'),
    ('diensten-ai', 'heroLead'),
    ('diensten-ai', 'crossrefTitel'),
    ('diensten-ai', 'ctaTitel'),
    ('diensten-strategie', 'metaTitle'),
    ('diensten-strategie', 'metaDescription'),
    ('diensten-strategie', 'badgeLabel'),
    ('diensten-strategie', 'heroTitleStart'),
    ('diensten-strategie', 'heroLead'),
    ('diensten-strategie', 'instapTitel'),
    ('diensten-strategie', 'instapTekst'),
    ('diensten-strategie', 'instapKnop'),
    ('diensten-strategie', 'crossrefTitel'),
    ('diensten-strategie', 'ctaTitel'),
    ('sectoren', 'heroTitleStart'),
    ('sectoren', 'heroAccent'),
    ('sectoren', 'heroLead'),
    ('sectoren', 'werkwijzeKicker'),
    ('sectoren', 'werkwijzeTitel'),
    ('sectoren', 'wijze1Titel'),
    ('sectoren', 'wijze1Tekst'),
    ('sectoren', 'wijze2Titel'),
    ('sectoren', 'wijze2Tekst'),
    ('sectoren', 'wijze3Titel'),
    ('sectoren', 'wijze3Tekst'),
    ('sectoren', 'ctaTitel'),
    ('werken-bij', 'heroTitleStart'),
    ('werken-bij', 'heroAccent'),
    ('werken-bij', 'heroLead'),
    ('werken-bij', 'groeiKicker'),
    ('werken-bij', 'groeiTitel'),
    ('werken-bij', 'groeiIntro'),
    ('werken-bij', 'groei1Titel'),
    ('werken-bij', 'groei1Tekst'),
    ('werken-bij', 'groei2Titel'),
    ('werken-bij', 'groei2Tekst'),
    ('werken-bij', 'groei3Titel'),
    ('werken-bij', 'groei3Tekst'),
    ('werken-bij', 'tpKicker'),
    ('werken-bij', 'tpTitel'),
    ('werken-bij', 'tpIntro'),
    ('werken-bij', 'tp1Titel'),
    ('werken-bij', 'tp1Tekst'),
    ('werken-bij', 'tp2Titel'),
    ('werken-bij', 'tp2Tekst'),
    ('werken-bij', 'tp3Titel'),
    ('werken-bij', 'tp3Tekst'),
    ('werken-bij', 'cultuurKicker'),
    ('werken-bij', 'cultuurTitel'),
    ('werken-bij', 'cultuurP'),
    ('werken-bij', 'cultuur1'),
    ('werken-bij', 'cultuur2'),
    ('werken-bij', 'cultuur3'),
    ('werken-bij', 'cultuur4'),
    ('werken-bij', 'ctaTitel'),
    ('werken-bij', 'geenMatchVoor'),
    ('werken-bij', 'geenVacatures'),
    ('werken-bij', 'openSollLink'),
    ('werken-bij', 'belRegel'),
    ('werken-bij', 'openSollKop'),
    ('werken-bij', 'openSollIntro'),
    ('werken-bij', 'openSollNoot'),
    ('werken-bij', 'cultuurFotoAlt'),
    ('klantverhalen', 'metaTitle'),
    ('klantverhalen', 'metaDescription'),
    ('klantverhalen', 'heroKicker'),
    ('klantverhalen', 'heroTitleStart'),
    ('klantverhalen', 'heroAccent'),
    ('klantverhalen', 'heroTitleEnd'),
    ('klantverhalen', 'heroLead'),
    ('klantverhalen', 'uitgelichtKicker'),
    ('klantverhalen', 'beloftesKicker'),
    ('klantverhalen', 'beloftesTitel'),
    ('klantverhalen', 'beloftesIntro'),
    ('klantverhalen', 'ctaTitel'),
    ('inzichten', 'metaTitle'),
    ('inzichten', 'metaDescription'),
    ('inzichten', 'heroKicker'),
    ('inzichten', 'heroTitleStart'),
    ('inzichten', 'heroAccent'),
    ('inzichten', 'heroTitleEnd'),
    ('inzichten', 'heroLead'),
    ('inzichten', 'leadTitel'),
    ('inzichten', 'leadTekst'),
    ('inzichten', 'artikelLeadTitel'),
    ('inzichten', 'artikelLeadTekst'),
    ('privacy', 'metaTitle'),
    ('privacy', 'metaDescription'),
    ('privacy', 'heroTitel'),
    ('privacy', 'heroLead'),
    ('privacy', 'body')
)
select r.soort,
       r.slug,
       count(*) as ontbreekt,
       string_agg(v.veld, ', ' order by v.veld) as velden
  from rijen r
  join verwacht v on v.soort = r.soort
 where not (r.data ? v.veld)
 group by r.soort, r.slug
union all
select 'paginas',
       p.slug,
       count(*),
       string_agg(v.veld, ', ' order by v.veld)
  from paginarijen p
  join paginaverwacht v on v.slug = p.slug
 where not (p.data ? v.veld)
 group by p.slug
 order by 1, 2;
