-- Vacatures uit de lucht bij livegang (9 september 2026).
--
-- De seed in lib/vacatures.ts is leeggemaakt, dus de site toont niets meer.
-- Deze rijen zetten de teksten als CONCEPT in het CMS, zodat ze niet
-- verdwijnen: een vacature terugzetten is daarna één statuswissel naar 'live'
-- in /admin/vacatures. Idempotent — bestaat de rij al, dan gaat alleen de
-- status naar concept en blijft de redactie erop intact.

insert into cms_vacatures (slug, titel, status, volgorde, data)
values ('medior-mendix-consultant', 'Medior Mendix Consultant', 'concept', 0, '{"functietitel":"Medior Mendix Consultant","discipline":"Mendix · Medior","locatie":"Utrecht / hybride","tags":["Mendix","Medior","Utrecht / hybride"],"intro":"Als Mendix Consultant ontwerp en implementeer jij slimme IT-oplossingen die bedrijven helpen hun grootste uitdagingen aan te gaan. Bij ons krijg je de vrijheid om jouw expertise en ambitie te combineren met onze visie op strategische IT-partnerships. Van het ontwikkelen van AI-capabilities tot het leiden van projecten bij klanten: jouw bijdrage is essentieel voor ons gezamenlijke succes.","secties":[{"titel":"Waarom begin jij met enthousiasme je werkdag?","items":["Het uitbouwen van AI-capabilities in Mendix-omgevingen","Het bouwen van klantrelaties door intensieve partnerships te ontwikkelen","Coaching van junior en medior collega''s","Het leveren van strategisch advies aan klanten en hen meenemen in digitale transformaties","Het ontwikkelen van innovatieve oplossingen die onze partners helpen groeien"]},{"titel":"Wie ben jij?","items":["Minimaal 2,5 jaar ervaring als Mendix Consultant of een bewezen snelle leercurve","Advanced of Expert Mendix-certificering","Kennis van of affiniteit met AI","HBO- of WO-werk- en denkniveau","Ervaring met Scrum/Agile werken","Enthousiast om onze kernwaarden (Idealistisch, Jij op 1, Synergie, Transparantie, Groei & Vooruitgang) uit te dragen","Initiatiefrijk en gemotiveerd om zowel de organisatie als jezelf continu te verbeteren"]},{"titel":"Wat bieden wij jou?","items":["Een uitstekend salaris","Een jaarcontract met uitzicht op een vast dienstverband","Onbeperkt vakantiedagen","Jouw persoonlijke groeipad en opleidingen op maat","Uitdagende projecten bij toonaangevende klanten","Mobiliteitsopties zoals een OV-chipkaart","Een pensioenregeling","Een organisatie waar jij écht invloed hebt op strategie en richting","Een mensgerichte ervaring waarin jouw welzijn en groei centraal staan","Een innovatieve omgeving waar jouw creativiteit en ondernemerschap wordt gestimuleerd"]},{"titel":"Het sollicitatieproces","items":["Een eerste gesprek waarin we jouw ambitie en ervaring bespreken","Een technisch assessment/gesprek","Een gesprek voor culturele fit","Een voorstel dat past bij jouw wensen"]}],"facts":{"team":"Mendix","niveau":"Medior","locatie":"Utrecht / hybride","uren":"In overleg","salaris":"Marktconform"},"employmentType":"FULL_TIME","gepubliceerdOp":"2025-06-01"}'::jsonb)
on conflict (slug) do update set status = 'concept';

insert into cms_vacatures (slug, titel, status, volgorde, data)
values ('senior-mendix-consultant', 'Senior Mendix Consultant', 'concept', 1, '{"functietitel":"Senior Mendix Consultant","discipline":"Mendix · Senior","locatie":"Utrecht / hybride","tags":["Mendix","Senior","Utrecht / hybride"],"intro":"Als Mendix Consultant ontwerp en implementeer jij slimme IT-oplossingen die bedrijven helpen hun grootste uitdagingen aan te gaan. Bij ons krijg je de vrijheid om jouw expertise en ambitie te combineren met onze visie op strategische IT-partnerships. Van het ontwikkelen van AI-capabilities tot het leiden van projecten bij klanten: jouw bijdrage is essentieel voor ons gezamenlijke succes.","secties":[{"titel":"Waarom begin jij met enthousiasme je werkdag?","items":["Het uitbouwen van AI-capabilities in Mendix-omgevingen","Het bouwen van klantrelaties door intensieve partnerships te ontwikkelen","Coaching van junior en medior collega''s","Het leveren van strategisch advies aan klanten en hen meenemen in digitale transformaties","Het ontwikkelen van innovatieve oplossingen die onze partners helpen groeien"]},{"titel":"Wie ben jij?","items":["Minimaal 4 jaar ervaring als Mendix Consultant of een bewezen snelle leercurve","Advanced of Expert Mendix-certificering","Kennis van of affiniteit met AI","HBO- of WO-werk- en denkniveau","Ervaring met Scrum/Agile werken","Enthousiast om onze kernwaarden (Idealistisch, Jij op 1, Synergie, Transparantie, Groei & Vooruitgang) uit te dragen","Initiatiefrijk en gemotiveerd om zowel de organisatie als jezelf continu te verbeteren"]},{"titel":"Wat bieden wij jou?","items":["Een uitstekend salaris met een aantrekkelijk bonuscomponent","Een jaarcontract met uitzicht op een vast dienstverband","Onbeperkt vakantiedagen","Jouw persoonlijke groeipad en opleidingen op maat","Uitdagende projecten bij toonaangevende klanten","Mobiliteitsopties zoals een OV-chipkaart","Een pensioenregeling","Een organisatie waar jij écht invloed hebt op strategie en richting","Een mensgerichte ervaring waarin jouw welzijn en groei centraal staan","Een innovatieve omgeving waar jouw creativiteit en ondernemerschap wordt gestimuleerd"]},{"titel":"Het sollicitatieproces","items":["Een eerste gesprek waarin we jouw ambitie en ervaring bespreken","Een technisch assessment/gesprek","Een gesprek voor culturele fit","Een voorstel dat past bij jouw wensen"]}],"facts":{"team":"Mendix","niveau":"Senior","locatie":"Utrecht / hybride","uren":"In overleg","salaris":"Marktconform, met bonuscomponent"},"employmentType":"FULL_TIME","gepubliceerdOp":"2025-03-01"}'::jsonb)
on conflict (slug) do update set status = 'concept';

-- Controle: beide rijen horen nu op concept te staan.
select slug, titel, status from cms_vacatures order by volgorde;
